### ISSUE TITLE
libimobiledevice for Windows

### ISSUE THREAD

**Issue by sack112007** [libimobiledevice/libimobiledevice#24]
Hi,
It will be a great help if someone can give me a step by step details about building libimobiledevice for windows 7.
This issue is very much similar to Issue#11.But no one is replying on that thread.

Please help me out.:(

**Comment by qmfrederik** [comment]
Hi,

We got libimobiledevice to compile on Windows using MinGW. Since a lot of people seem to have issues compiling it, we've created a binary distribution of MinGW for Windows.

You can find the binary files [here](http://quamotion.mobi/iMobileDevice/Download)

If you want to compile from source yourself, you can download all the packages with the source files from [our website](http://quamotion.mobi/iMobileDevice/Article/version). Most of them come straight from the libimobiledevice repos; some small patches were required and we published them [on our GitHub repository](http://github.com/quamotion).

Hope it helps,

Frederik

**Comment by JeffryBooher** [comment]
@qmfrederik can you maybe document the steps to build it on Windows?

**Comment by qmfrederik** [comment]
@JeffryBooher  Sure, we've published them online at http://quamotion.mobi/iMobileDevice/Article/compiling

Any questions feel free to ask!

**Comment by hyunmin90** [comment]
@qmfrederik 
Hi qmfred have you ever ran in to an issue when make install on libusbmuxd? I am running in to compiler error for make install .

It says that 

libusbmuxd.c:46:26: error: expected ';', ',' or ')' before numeric constant
 #define sleep(x) Sleep(x*1000)
                          ^
libusbmuxd.c:46:25: error: expected ';', ',' or ')' before '*' token
 #define sleep(x) Sleep(x*1000)
                         ^
make[2]: *** [libusbmuxd.lo] Error 1
make[2]: Leaving directory `/home/Naver/libusbmuxd-master/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/Naver/libusbmuxd-master'
make: *** [all] Error 2
