### ISSUE TITLE
Can not build on Mac High Sierra.

### ISSUE THREAD

**Issue by pablichjenkov** [libimobiledevice/libimobiledevice#619]
When executing ./autoconf.sh I got the following output. What I am missing?

./configure: line 15993: syntax error near unexpected token `libusbmuxd,'
./configure: line 15993: `PKG_CHECK_MODULES(libusbmuxd, libusbmuxd >= $LIBUSBMUXD_VERSION)'

**Comment by abardallis** [comment]
Same issue here! Any progress?

**Comment by HHMedic** [comment]
I has the same quetion, but abardallis's solution doesnot help.

**Comment by nikias** [comment]
You need to install pkg-config... is anyone actually reading README / Requirements ?

**Comment by dandv** [comment]
@nikias: this dependency is a low-level one when used in higher level tasks like [remote debugging Chrome on iOS](http://jonsadka.com/blog/how-to-debug-a-chrome-specific-bug-on-ios-using-remote-debugging/), so people might never see the README when the follow instructions like `brew install --HEAD libimobiledevice`.

Anyway, thanks for the answer, it worked! (`brew link --overwrite pkg-config`, more specifically, since pkg-config was already installed on my machine).

**Comment by MRZHL** [comment]
Thanks for answer  , use brew link --overwrite pkg-config ,sucess
