### ISSUE TITLE
diagnostic  iphone by libimobiledevice libs

### ISSUE THREAD

**Issue by amzil** [libimobiledevice/libimobiledevice#658]
Hello, 

Is it possible to know if the internal component it's works (Wifi, GPS, accelerometer, GSM , tactile chipset) and also a status of the touch ID (home buttons) it's the original one or not.

I have already test idevicediagnostics diagnostics commande 

-----

	<key>GasGauge</key>
	<dict>
		<key>CycleCount</key>
		<integer>275</integer>
		<key>DesignCapacity</key>
		<integer>1751</integer>
		<key>FullChargeCapacity</key>
		<integer>1600</integer>
		<key>Status</key>
		<string>Success</string>
	</dict>
	<key>HDMI</key>
	<dict>
		<key>Connection</key>
		<string>Unplugged</string>
		<key>Status</key>
		<string>Success</string>
	</dict>
	<key>NAND</key>
	<dict>
		<key>Status</key>
		<string>NANDInfoFailed</string>
	</dict>
	<key>WiFi</key>
-----
@nikias have you any idea ?

**Comment by abdulzeedo** [comment]
Are you using it for business purposes? Because it looks so... Please be aware that this library is not for commercial purposes... You should contact its creators who own a company and they will be happy to provide you with solutions. (at least this is what people say on this type of questions...I am just helping you out)
